# 2.2 添加以下配置
server:
  # 端口
  port: 8762
spring:
  application:
    # 服务名称
    name: service-provider
eureka:
  client:
    service-url:
      #服务注册地址
      defaultZone: http://localhost:8761/eureka/
