# 1.2 将application.properties改为application.yml

# 1.3 添加以下内容
server:
  # 运行端口
  port: 8761
eureka:
  # 实例
  instance:
    # 主机名
    hostname: localhost
  client:
    # 表示是否需要将自己注册到Eureka Server上
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息
    fetch-registry: false
    # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/